services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: admin() 
      MONGO_INITDB_DATABASE: admin 
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db
volumes:
  database:
